workspace(name = "retool")

###
### Reason Rules!
###

local_repository(
    name = "com_github_ostera_rules_reason",
    path = "../",
)

# rules_reason_version = "f8b956b147bfcf22c90480e7ebea32e6769c1fe0" # HEAD
#
# http_archive(
#     name = "com_github_ostera_rules_reason",
#     sha256 = "",
#     strip_prefix = "rules_reason-%s" % (rules_reason_version,),
#     urls = ["https://github.com/ostera/rules_reason/archive/%s.zip" % (rules_reason_version,)],
#     )
#
###
### Nix Repositories
###

load(
    "@com_github_ostera_rules_reason//reason/repositories:nix.bzl",
    "nix_repositories",
)

nix_repositories(
    nix_sha256 = "28121f6eb3d6c5b4c1fc9f716953ce8b0a793b841d0e9de095977b3ade06f92d",
    nix_version = "20a78f74f8ac70d1099ff0d214cd00b25820da03",
)

###
### Register Reason Toolchain
###

load(
    "@com_github_ostera_rules_reason//reason:def.bzl",
    "reason_register_toolchains",
)

reason_register_toolchains(
    bs_sha256 = "db3f37eb27bc1653c3045e97adaa83e800dff55ce093d78ddfe85e85165e2125",
    bs_version = "939ef1e1e874c80ff9df74b16dab1dbe2e2df289",
    nixpkgs_revision = "d91a8a6ece07f5a6df82aa5dc02030d9c6724c27",
    nixpkgs_sha256 = "0c5291bcf7d909cc4b18a24effef03f717d6374de377f91324725c646d494857",
)
